"""aggiunto campo original_relative_path

Revision ID: 05109b681da9
Revises: 527682c78fb5
Create Date: 2025-01-10 16:37:18.869246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05109b681da9'
down_revision = '527682c78fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_relative_path', sa.String(length=512), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('original_relative_path')

    # ### end Alembic commands ###
