"""aggiunta tabelle per casi e file

Revision ID: 527682c78fb5
Revises: 7f49b8056673
Create Date: 2025-01-07 16:23:55.664354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527682c78fb5'
down_revision = '7f49b8056673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('file_metadata', sa.JSON(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('cases')
    # ### end Alembic commands ###
